In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import os
import cv2

In [2]:
df = pd.read_csv("./stanford_dogs.csv")
df.head()

path         filename  width  \
0  Images/n02085620-Chihuahua/n02085620_10074.jpg  n02085620_10074    333   
1  Images/n02085620-Chihuahua/n02085620_10131.jpg  n02085620_10131    395   
2  Images/n02085620-Chihuahua/n02085620_10621.jpg  n02085620_10621    500   
3   Images/n02085620-Chihuahua/n02085620_1073.jpg   n02085620_1073    345   
4  Images/n02085620-Chihuahua/n02085620_10976.jpg  n02085620_10976    322   

   height  depth       name  xmin  ymin  xmax  ymax  
0     500      3  Chihuahua    25    10   276   498  
1     495      3  Chihuahua    49     9   393   493  
2     298      3  Chihuahua   142    43   335   250  
3     500      3  Chihuahua     0    27   312   498  
4     484      3  Chihuahua    90   104   242   452

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22126 entries, 0 to 22125
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   path      22126 non-null  object
 1   filename  22126 non-null  object
 2   width     22126 non-null  int64 
 3   height    22126 non-null  int64 
 4   depth     22126 non-null  int64 
 5   name      22126 non-null  object
 6   xmin      22126 non-null  int64 
 7   ymin      22126 non-null  int64 
 8   xmax      22126 non-null  int64 
 9   ymax      22126 non-null  int64 
dtypes: int64(7), object(3)
memory usage: 1.7+ MB


In [4]:
df.isna().sum()

path        0
filename    0
width       0
height      0
depth       0
name        0
xmin        0
ymin        0
xmax        0
ymax        0
dtype: int64

In [5]:
df.describe()

width        height    depth          xmin          ymin  \
count  22126.000000  22126.000000  22126.0  22126.000000  22126.000000   
mean     444.466962    384.804077      3.0     81.289704     59.522779   
std      141.479881    123.644156      0.0     81.246879     61.769030   
min       97.000000    100.000000      3.0      0.000000      0.000000   
25%      371.000000    333.000000      3.0     16.000000     15.000000   
50%      500.000000    375.000000      3.0     60.000000     42.000000   
75%      500.000000    448.000000      3.0    127.000000     87.000000   
max     3264.000000   2562.000000      3.0   1253.000000   1548.000000   

               xmax          ymax  
count  22126.000000  22126.000000  
mean     362.671879    350.203742  
std      130.067137    121.931509  
min       28.000000     31.000000  
25%      286.000000    285.000000  
50%      357.000000    335.000000  
75%      438.000000    392.000000  
max     2735.000000   2457.000000

In [6]:
df['name'].value_counts()

name
Afghan_hound          287
Maltese_dog           264
Irish_wolfhound       263
Leonberg              256
Scottish_deerhound    246
                     ... 
affenpinscher         153
malinois              153
groenendael           152
Pekinese              152
redbone               151
Name: count, Length: 120, dtype: int64

In [7]:
ct = 0
for ind in df.index:
    path = df['path'][ind]
    name = df['name'][ind]
    x1 = df['xmin'][ind]
    x2 = df['xmax'][ind]
    y1 = df['ymin'][ind]
    y2 = df['ymax'][ind]
    try:
        img = cv2.imread(path)
        crop = img[y1:y2,x1:x2]
        os.makedirs("DogsImages/"+name, exist_ok=True)
        fl = "DogsImages/" + name + "/sample_" + str(ind+1) + ".jpg"
        cv2.imwrite(fl, crop)
    except:
        ct += 1
        # print(path)
        print(ct,name,path)

In [8]:
img = cv2.imread(path)
print(img)
crop = img[12:120,120:240]
os.makedirs("DogsImages/"+name, exist_ok=True)
cv2.imwrite("test.jpg", crop)

[[[115 159 122]
  [115 159 122]
  [114 159 120]
  ...
  [ 95 125 126]
  [101 134 127]
  [110 145 131]]

 [[113 157 120]
  [113 157 120]
  [113 158 119]
  ...
  [110 138 138]
  [114 147 140]
  [113 146 131]]

 [[111 156 117]
  [111 156 117]
  [112 157 118]
  ...
  [ 89 116 113]
  [101 133 122]
  [107 139 122]]

 ...

 [[ 90 136 137]
  [ 87 131 130]
  [106 148 147]
  ...
  [103 141 146]
  [ 99 137 142]
  [ 95 133 138]]

 [[ 95 139 138]
  [ 75 120 117]
  [ 88 131 128]
  ...
  [109 150 153]
  [104 147 150]
  [ 98 140 145]]

 [[ 79 124 121]
  [ 73 118 115]
  [ 60 100  98]
  ...
  [115 158 161]
  [112 155 158]
  [104 149 153]]]


True